language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='scipy reproject psutil cython astroscrappy scikit-image memory_profiler'
        - PIP_DEPENDENCIES=''
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - CONDA_CHANNELS='astropy'
        - ASTROPY_USE_SYSTEM_PYTEST=1

    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:
        - env: PYTHON_VERSION=3.7
               SETUP_CMD='egg_info'

        # Do a windows run
        - os: windows
          env: PYTHON_VERSION=3.7
               ASTROPY_VERSION=stable
               NUMPY_VERSION=stable

        # Try Astropy development versions. This requires them to be
        # compiled during setup which takes some time.
        # Building against numpy dev was removed because it was causing
        # failures due to numpy dev/astropy dev conflicts unresolvable
        # in ccdproc.
        - env: PYTHON_VERSION=3.7
               ASTROPY_VERSION=development
               NUMPY_VERSION=stable
               SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings
        - env: PYTHON_VERSION=3.7
               SETUP_CMD='build_docs -w'
               CONDA_DEPENDENCIES="$CONDA_DEPENDENCIES sphinx-astropy"

        # Do coverage tests for both latest Python versions
        - env: PYTHON_VERSION=3.7
               ASTROPY_VERSION=3
               SETUP_CMD='test --coverage'

        # Check compatibility with the current astropy LTS release
        - python: 3.6
          env: ASTROPY_VERSION=2
               PYTEST_VERSION=3.6

        - python: 3.5
          env: NUMPY_VERSION=1.13

        - python: 3.6
          env: NUMPY_VERSION=1.14

        # Try numpy pre-release version. This runs only when a pre-release
        # is available on pypi.
        - env: PYTHON_VERSION=3.7
               NUMPY_VERSION=prerelease

        # pycodestyle test, see setup.cfg for tested pep8 warnings/errors
        - env: PYTHON_VERSION=3.7
               MAIN_CMD='pycodestyle ccdproc --count  --show-source --show-pep8'
               SETUP_CMD=''

install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh


script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='ccdproc/tests/coveragerc'; fi
